2017-11-28 11:16:40,922 ERROR zeus_ads_all_error 140557615617792 - [AdCreativeAllWorking] [_get_ecommerce_link] Exception, object_story_id:515578665135168_2536305179729163, reason:[Errno bad handshake] (-1, 'Unexpected EOF')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 232, in _get_ecommerce_link
    response = requests.get(url, params=params).text
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad handshake] (-1, 'Unexpected EOF')
2017-11-28 11:19:22,627 ERROR zeus_ads_all_error 140557626107648 - [AdCreativeAllWorking] [_get_ad_creatives] Exception, ad_id:6076261125480, reason:('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 175, in _get_ad_creatives
    ad_creatives = self.fb_api.get_adcreative_by_adid(ad_id)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 391, in get_adcreative_by_adid
    AdCreative.Field.status
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 264, in get_ad_creatives
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
2017-11-28 11:31:26,404 ERROR zeus_ads_all_error 140557615617792 - [AdCreativeAllWorking] [_get_ad_creatives] Exception, ad_id:6081673046638, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 175, in _get_ad_creatives
    ad_creatives = self.fb_api.get_adcreative_by_adid(ad_id)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 391, in get_adcreative_by_adid
    AdCreative.Field.status
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 264, in get_ad_creatives
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,464 ERROR zeus_ads_all_error 140557615617792 - [AdCreativeAllWorking] [_get_ad_insights] Exception, ad_id:6082044239238, start_dt:2017-11-27, stop_dt:2017-11-27, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_all_working.py", line 31, in _get_ad_insights
    ad_insights = self.fb_api.get_ad_insights(ad_id, '', start_dt, stop_dt)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 355, in get_ad_insights
    insights = ad.get_insights(params=params)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 384, in get_insights
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,545 ERROR zeus_ads_all_error 140557594638080 - [AdCreativeAllWorking] [_get_ads_info_by_adset] Exception, adset_id:6094818597786, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 157, in _get_ads_info_by_adset
    ads_info = self.fb_api.get_ads_info_by_adset(adset_id)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 320, in get_ads_info_by_adset
    Ad.Field.status,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/adset.py", line 454, in get_ads
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,548 ERROR zeus_ads_all_error 140557584148224 - [AdCreativeAllWorking] [_get_ads_info_by_adset] Exception, adset_id:6098191315965, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 157, in _get_ads_info_by_adset
    ads_info = self.fb_api.get_ads_info_by_adset(adset_id)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 320, in get_ads_info_by_adset
    Ad.Field.status,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/adset.py", line 454, in get_ads
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,592 ERROR zeus_ads_all_error 140557233944320 - [AdCreativeAllWorking] [_get_ad_insights] Exception, ad_id:6078016822333, start_dt:2017-11-27, stop_dt:2017-11-27, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_all_working.py", line 31, in _get_ad_insights
    ad_insights = self.fb_api.get_ad_insights(ad_id, '', start_dt, stop_dt)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 355, in get_ad_insights
    insights = ad.get_insights(params=params)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 384, in get_insights
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,676 ERROR zeus_ads_all_error 140557223454464 - [AdCreativeAllWorking] [_get_ads_info_by_adset] Exception, adset_id:6085315881030, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_base.py", line 157, in _get_ads_info_by_adset
    ads_info = self.fb_api.get_ads_info_by_adset(adset_id)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 320, in get_ads_info_by_adset
    Ad.Field.status,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/adset.py", line 454, in get_ads
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:26,763 ERROR zeus_ads_all_error 140557636597504 - [AdCreativeAllWorking] [_get_ad_insights] Exception, ad_id:6087358567302, start_dt:2017-11-27, stop_dt:2017-11-27, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_all_working.py", line 31, in _get_ad_insights
    ad_insights = self.fb_api.get_ad_insights(ad_id, '', start_dt, stop_dt)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 355, in get_ad_insights
    insights = ad.get_insights(params=params)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 384, in get_insights
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1013, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 360, in _read_status
    line = self.fp.readline()
  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
2017-11-28 11:31:27,046 ERROR zeus_ads_all_error 140557605127936 - [AdCreativeAllWorking] [_get_ad_insights] Exception, ad_id:6085173888624, start_dt:2017-11-27, stop_dt:2017-11-27, reason:(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/collector/adcreative/adcreative_all_working.py", line 31, in _get_ad_insights
    ad_insights = self.fb_api.get_ad_insights(ad_id, '', start_dt, stop_dt)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebook_interface.py", line 355, in get_ad_insights
    insights = ad.get_insights(params=params)
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/adobjects/ad.py", line 384, in get_insights
    return request.execute()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 653, in execute
    cursor.load_next_page()
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 810, in load_next_page
    params=self.params,
  File "/home/liuyang/wwwroot/zeus/zeus_data_collector_v2/lib/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python2.7/httplib.py", line 941, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 975, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 937, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 797, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 773, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    sent = self._send_until_done(data)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 198, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 950, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
SysCallError: (104, 'ECONNRESET')
